<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
 
/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function ucb_person_title_form_node_ucb_person_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    $form['title']['#access'] = FALSE;
    $form['#entity_builders'][] = 'ucb_person_title_builder';
}

// Handles Person Page edit form
function ucb_person_title_form_node_ucb_person_edit_form_alter(&$form, FormStateInterface $form_state, $form_id){
  $form['title']['#access'] = FALSE;
  $form['#entity_builders'][] = 'ucb_person_title_builder';
}
 
/**
 * Title builder for Person Page & Person Page Edit Form.
 *
 * @param $entity_type
 * @param \Drupal\node\NodeInterface $node
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function ucb_person_title_builder($entity_type, NodeInterface $node, $form, FormStateInterface $form_state) {
  $last = $node->get('field_ucb_person_last_name')->value;
  $first = $node->get('field_ucb_person_first_name')->value;

  // Remove whitespace
  $last = trim($last);
  $first = trim($first);
 
  // Set title
  $node->setTitle( $first . ' ' . $last);
}
